apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checluster
  namespace: openshift-gitops
spec:
  destination:
    namespace: spring-petclinic
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: devspaces 
    repoURL: https://github.com/rht-labs-events/summit-lab-2023.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
