apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: devspaces
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/lab-content/operators/devspaces
    # repoURL: https://github.com/rht-labs-events/summit-lab-2023.git
    # targetRevision: main
    repoURL: https://github.com/etsauer/summit-lab-2023.git
    targetRevision: add-pelorus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
